package com.ks.modelo.entities;
// Generated 15-ago-2017 22:28:36 by Hibernate Tools 5.2.3.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Cliente generated by hbm2java
 */
@Entity
@Table(name = "cliente", catalog = "kumibd")
public class Cliente implements java.io.Serializable {

	private Long id;
	private String codigo;
	private String razonSocial;
	private String nombreComercio;
	private String sucursal;
	private String rif;
	private String telefono;
	private String telefonoLocal;
	private String email1;
	private String email2;
	private String email3;
	private String email4;
	private String direccionFiscal;
	private String direccionDespacho;
	private Date horaIniLab;
	private Date horaFinLab;
	private Date horaIniDescanso;
	private Date horaFinDescanso;
	private Date horaIniDespacho;
	private Date horaFinDespacho;
	private int idTipoContribuyente;
	private Long idVendedor;
	private int idZona;
	private String representante;
	private Integer idCondPago;
	private Date FModif;
	private Date FAlta;
	private Set<Sucursal> sucursals = new HashSet<Sucursal>(0);

	public Cliente() {
	}

	public Cliente(String codigo, String razonSocial, int idTipoContribuyente, int idZona, Date FModif, Date FAlta) {
		this.codigo = codigo;
		this.razonSocial = razonSocial;
		this.idTipoContribuyente = idTipoContribuyente;
		this.idZona = idZona;
		this.FModif = FModif;
		this.FAlta = FAlta;
	}

	public Cliente(String codigo, String razonSocial, String nombreComercio, String sucursal, String rif,
			String telefono, String telefonoLocal, String email1, String email2, String email3, String email4,
			String direccionFiscal, String direccionDespacho, Date horaIniLab, Date horaFinLab, Date horaIniDescanso,
			Date horaFinDescanso, Date horaIniDespacho, Date horaFinDespacho, int idTipoContribuyente, Long idVendedor,
			int idZona, String representante, Integer idCondPago, Date FModif, Date FAlta, Set<Sucursal> sucursals) {
		this.codigo = codigo;
		this.razonSocial = razonSocial;
		this.nombreComercio = nombreComercio;
		this.sucursal = sucursal;
		this.rif = rif;
		this.telefono = telefono;
		this.telefonoLocal = telefonoLocal;
		this.email1 = email1;
		this.email2 = email2;
		this.email3 = email3;
		this.email4 = email4;
		this.direccionFiscal = direccionFiscal;
		this.direccionDespacho = direccionDespacho;
		this.horaIniLab = horaIniLab;
		this.horaFinLab = horaFinLab;
		this.horaIniDescanso = horaIniDescanso;
		this.horaFinDescanso = horaFinDescanso;
		this.horaIniDespacho = horaIniDespacho;
		this.horaFinDespacho = horaFinDespacho;
		this.idTipoContribuyente = idTipoContribuyente;
		this.idVendedor = idVendedor;
		this.idZona = idZona;
		this.representante = representante;
		this.idCondPago = idCondPago;
		this.FModif = FModif;
		this.FAlta = FAlta;
		this.sucursals = sucursals;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "CODIGO", nullable = false, length = 7)
	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	@Column(name = "RAZON_SOCIAL", nullable = false, length = 100)
	public String getRazonSocial() {
		return this.razonSocial;
	}

	public void setRazonSocial(String razonSocial) {
		this.razonSocial = razonSocial;
	}

	@Column(name = "NOMBRE_COMERCIO", length = 100)
	public String getNombreComercio() {
		return this.nombreComercio;
	}

	public void setNombreComercio(String nombreComercio) {
		this.nombreComercio = nombreComercio;
	}

	@Column(name = "SUCURSAL", length = 50)
	public String getSucursal() {
		return this.sucursal;
	}

	public void setSucursal(String sucursal) {
		this.sucursal = sucursal;
	}

	@Column(name = "RIF", length = 12)
	public String getRif() {
		return this.rif;
	}

	public void setRif(String rif) {
		this.rif = rif;
	}

	@Column(name = "TELEFONO", length = 12)
	public String getTelefono() {
		return this.telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

	@Column(name = "TELEFONO_LOCAL", length = 12)
	public String getTelefonoLocal() {
		return this.telefonoLocal;
	}

	public void setTelefonoLocal(String telefonoLocal) {
		this.telefonoLocal = telefonoLocal;
	}

	@Column(name = "EMAIL_1", length = 50)
	public String getEmail1() {
		return this.email1;
	}

	public void setEmail1(String email1) {
		this.email1 = email1;
	}

	@Column(name = "EMAIL_2", length = 50)
	public String getEmail2() {
		return this.email2;
	}

	public void setEmail2(String email2) {
		this.email2 = email2;
	}

	@Column(name = "EMAIL_3", length = 50)
	public String getEmail3() {
		return this.email3;
	}

	public void setEmail3(String email3) {
		this.email3 = email3;
	}

	@Column(name = "EMAIL_4", length = 50)
	public String getEmail4() {
		return this.email4;
	}

	public void setEmail4(String email4) {
		this.email4 = email4;
	}

	@Column(name = "DIRECCION_FISCAL", length = 200)
	public String getDireccionFiscal() {
		return this.direccionFiscal;
	}

	public void setDireccionFiscal(String direccionFiscal) {
		this.direccionFiscal = direccionFiscal;
	}

	@Column(name = "DIRECCION_DESPACHO", length = 200)
	public String getDireccionDespacho() {
		return this.direccionDespacho;
	}

	public void setDireccionDespacho(String direccionDespacho) {
		this.direccionDespacho = direccionDespacho;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "HORA_INI_LAB", length = 8)
	public Date getHoraIniLab() {
		return this.horaIniLab;
	}

	public void setHoraIniLab(Date horaIniLab) {
		this.horaIniLab = horaIniLab;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "HORA_FIN_LAB", length = 8)
	public Date getHoraFinLab() {
		return this.horaFinLab;
	}

	public void setHoraFinLab(Date horaFinLab) {
		this.horaFinLab = horaFinLab;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "HORA_INI_DESCANSO", length = 8)
	public Date getHoraIniDescanso() {
		return this.horaIniDescanso;
	}

	public void setHoraIniDescanso(Date horaIniDescanso) {
		this.horaIniDescanso = horaIniDescanso;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "HORA_FIN_DESCANSO", length = 8)
	public Date getHoraFinDescanso() {
		return this.horaFinDescanso;
	}

	public void setHoraFinDescanso(Date horaFinDescanso) {
		this.horaFinDescanso = horaFinDescanso;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "HORA_INI_DESPACHO", length = 8)
	public Date getHoraIniDespacho() {
		return this.horaIniDespacho;
	}

	public void setHoraIniDespacho(Date horaIniDespacho) {
		this.horaIniDespacho = horaIniDespacho;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "HORA_FIN_DESPACHO", length = 8)
	public Date getHoraFinDespacho() {
		return this.horaFinDespacho;
	}

	public void setHoraFinDespacho(Date horaFinDespacho) {
		this.horaFinDespacho = horaFinDespacho;
	}

	@Column(name = "ID_TIPO_CONTRIBUYENTE", nullable = false)
	public int getIdTipoContribuyente() {
		return this.idTipoContribuyente;
	}

	public void setIdTipoContribuyente(int idTipoContribuyente) {
		this.idTipoContribuyente = idTipoContribuyente;
	}

	@Column(name = "ID_VENDEDOR")
	public Long getIdVendedor() {
		return this.idVendedor;
	}

	public void setIdVendedor(Long idVendedor) {
		this.idVendedor = idVendedor;
	}

	@Column(name = "ID_ZONA", nullable = false)
	public int getIdZona() {
		return this.idZona;
	}

	public void setIdZona(int idZona) {
		this.idZona = idZona;
	}

	@Column(name = "REPRESENTANTE", length = 50)
	public String getRepresentante() {
		return this.representante;
	}

	public void setRepresentante(String representante) {
		this.representante = representante;
	}

	@Column(name = "ID_COND_PAGO")
	public Integer getIdCondPago() {
		return this.idCondPago;
	}

	public void setIdCondPago(Integer idCondPago) {
		this.idCondPago = idCondPago;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "F_MODIF", nullable = false, length = 19)
	public Date getFModif() {
		return this.FModif;
	}

	public void setFModif(Date FModif) {
		this.FModif = FModif;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "F_ALTA", nullable = false, length = 19)
	public Date getFAlta() {
		return this.FAlta;
	}

	public void setFAlta(Date FAlta) {
		this.FAlta = FAlta;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cliente")
	public Set<Sucursal> getSucursals() {
		return this.sucursals;
	}

	public void setSucursals(Set<Sucursal> sucursals) {
		this.sucursals = sucursals;
	}

}
