package com.ks.modelo.entities;
// Generated 02-sep-2017 16:26:57 by Hibernate Tools 5.2.3.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Cliente generated by hbm2java
 */
@Entity
@Table(name = "cliente", catalog = "kumibd", uniqueConstraints = @UniqueConstraint(columnNames = "CODIGO"))
public class Cliente implements java.io.Serializable {

	private Long id;
	private String codigo;
	private String razonSocial;
	private String nombreComercio;
	private String sucursal;
	private String rif;
	private String direccionFiscal;
	private Date FModif;
	private Date FAlta;
	private Set<Sucursal> sucursals = new HashSet<Sucursal>(0);

	public Cliente() {
	}

	public Cliente(String codigo, String razonSocial, Date FModif, Date FAlta) {
		this.codigo = codigo;
		this.razonSocial = razonSocial;
		this.FModif = FModif;
		this.FAlta = FAlta;
	}

	public Cliente(String codigo, String razonSocial, String nombreComercio, String sucursal, String rif,
			String direccionFiscal, Date FModif, Date FAlta, Set<Sucursal> sucursals) {
		this.codigo = codigo;
		this.razonSocial = razonSocial;
		this.nombreComercio = nombreComercio;
		this.sucursal = sucursal;
		this.rif = rif;
		this.direccionFiscal = direccionFiscal;
		this.FModif = FModif;
		this.FAlta = FAlta;
		this.sucursals = sucursals;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "CODIGO", unique = true, nullable = false, length = 7)
	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	@Column(name = "RAZON_SOCIAL", nullable = false, length = 100)
	public String getRazonSocial() {
		return this.razonSocial;
	}

	public void setRazonSocial(String razonSocial) {
		this.razonSocial = razonSocial;
	}

	@Column(name = "NOMBRE_COMERCIO", length = 100)
	public String getNombreComercio() {
		return this.nombreComercio;
	}

	public void setNombreComercio(String nombreComercio) {
		this.nombreComercio = nombreComercio;
	}

	@Column(name = "SUCURSAL", length = 50)
	public String getSucursal() {
		return this.sucursal;
	}

	public void setSucursal(String sucursal) {
		this.sucursal = sucursal;
	}

	@Column(name = "RIF", length = 12)
	public String getRif() {
		return this.rif;
	}

	public void setRif(String rif) {
		this.rif = rif;
	}

	@Column(name = "DIRECCION_FISCAL", length = 200)
	public String getDireccionFiscal() {
		return this.direccionFiscal;
	}

	public void setDireccionFiscal(String direccionFiscal) {
		this.direccionFiscal = direccionFiscal;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "F_MODIF", nullable = false, length = 19)
	public Date getFModif() {
		return this.FModif;
	}

	public void setFModif(Date FModif) {
		this.FModif = FModif;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "F_ALTA", nullable = false, length = 19)
	public Date getFAlta() {
		return this.FAlta;
	}

	public void setFAlta(Date FAlta) {
		this.FAlta = FAlta;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cliente")
	public Set<Sucursal> getSucursals() {
		return this.sucursals;
	}

	public void setSucursals(Set<Sucursal> sucursals) {
		this.sucursals = sucursals;
	}

}
