package com.ks.entities;
// Generated 15-ago-2017 22:28:36 by Hibernate Tools 5.2.3.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * OrdenCompra generated by hbm2java
 */
@Entity
@Table(name = "orden_compra", catalog = "kumibd")
public class OrdenCompra implements java.io.Serializable {

	private long id;
	private Persona persona;
	private Sucursal sucursal;
	private String codigo;
	private Integer credito;
	private String observaciones;
	private Set<ProductoOrden> productoOrdens = new HashSet<ProductoOrden>(0);

	public OrdenCompra() {
	}

	public OrdenCompra(long id, String codigo) {
		this.id = id;
		this.codigo = codigo;
	}

	public OrdenCompra(long id, Persona persona, Sucursal sucursal, String codigo, Integer credito,
			String observaciones, Set<ProductoOrden> productoOrdens) {
		this.id = id;
		this.persona = persona;
		this.sucursal = sucursal;
		this.codigo = codigo;
		this.credito = credito;
		this.observaciones = observaciones;
		this.productoOrdens = productoOrdens;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_PERSONA")
	public Persona getPersona() {
		return this.persona;
	}

	public void setPersona(Persona persona) {
		this.persona = persona;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_SUCURSAL")
	public Sucursal getSucursal() {
		return this.sucursal;
	}

	public void setSucursal(Sucursal sucursal) {
		this.sucursal = sucursal;
	}

	@Column(name = "CODIGO", nullable = false, length = 7)
	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	@Column(name = "CREDITO")
	public Integer getCredito() {
		return this.credito;
	}

	public void setCredito(Integer credito) {
		this.credito = credito;
	}

	@Column(name = "OBSERVACIONES", length = 500)
	public String getObservaciones() {
		return this.observaciones;
	}

	public void setObservaciones(String observaciones) {
		this.observaciones = observaciones;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ordenCompra")
	public Set<ProductoOrden> getProductoOrdens() {
		return this.productoOrdens;
	}

	public void setProductoOrdens(Set<ProductoOrden> productoOrdens) {
		this.productoOrdens = productoOrdens;
	}

}
