package com.ks.entities;
// Generated 15-ago-2017 22:28:36 by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ProductoOrden generated by hbm2java
 */
@Entity
@Table(name = "producto_orden", catalog = "kumibd")
public class ProductoOrden implements java.io.Serializable {

	private Long id;
	private OrdenCompra ordenCompra;
	private Producto producto;
	private long precioUnitario;
	private int cantidad;

	public ProductoOrden() {
	}

	public ProductoOrden(OrdenCompra ordenCompra, Producto producto, long precioUnitario, int cantidad) {
		this.ordenCompra = ordenCompra;
		this.producto = producto;
		this.precioUnitario = precioUnitario;
		this.cantidad = cantidad;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_ORDEN_COMPRA", nullable = false)
	public OrdenCompra getOrdenCompra() {
		return this.ordenCompra;
	}

	public void setOrdenCompra(OrdenCompra ordenCompra) {
		this.ordenCompra = ordenCompra;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_PRODUCTO", nullable = false)
	public Producto getProducto() {
		return this.producto;
	}

	public void setProducto(Producto producto) {
		this.producto = producto;
	}

	@Column(name = "PRECIO_UNITARIO", nullable = false, precision = 10, scale = 0)
	public long getPrecioUnitario() {
		return this.precioUnitario;
	}

	public void setPrecioUnitario(long precioUnitario) {
		this.precioUnitario = precioUnitario;
	}

	@Column(name = "CANTIDAD", nullable = false)
	public int getCantidad() {
		return this.cantidad;
	}

	public void setCantidad(int cantidad) {
		this.cantidad = cantidad;
	}

}
