package com.ks.entities;
// Generated 02-sep-2017 15:22:27 by Hibernate Tools 5.2.3.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * ProductoOrden generated by hbm2java
 */
@Entity
@Table(name = "producto_orden", catalog = "kumibd", uniqueConstraints = @UniqueConstraint(columnNames = {
		"ID_ORDEN_COMPRA", "ID_PRODUCTO" }))
public class ProductoOrden implements java.io.Serializable {

	private Long id;
	private OrdenCompra ordenCompra;
	private Producto producto;
	private long precioUnitario;
	private int cantidad;
	private Date FAlta;
	private Date FModif;

	public ProductoOrden() {
	}

	public ProductoOrden(OrdenCompra ordenCompra, Producto producto, long precioUnitario, int cantidad, Date FAlta,
			Date FModif) {
		this.ordenCompra = ordenCompra;
		this.producto = producto;
		this.precioUnitario = precioUnitario;
		this.cantidad = cantidad;
		this.FAlta = FAlta;
		this.FModif = FModif;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_ORDEN_COMPRA", nullable = false)
	public OrdenCompra getOrdenCompra() {
		return this.ordenCompra;
	}

	public void setOrdenCompra(OrdenCompra ordenCompra) {
		this.ordenCompra = ordenCompra;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_PRODUCTO", nullable = false)
	public Producto getProducto() {
		return this.producto;
	}

	public void setProducto(Producto producto) {
		this.producto = producto;
	}

	@Column(name = "PRECIO_UNITARIO", nullable = false, precision = 10, scale = 0)
	public long getPrecioUnitario() {
		return this.precioUnitario;
	}

	public void setPrecioUnitario(long precioUnitario) {
		this.precioUnitario = precioUnitario;
	}

	@Column(name = "CANTIDAD", nullable = false)
	public int getCantidad() {
		return this.cantidad;
	}

	public void setCantidad(int cantidad) {
		this.cantidad = cantidad;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "F_ALTA", nullable = false, length = 19)
	public Date getFAlta() {
		return this.FAlta;
	}

	public void setFAlta(Date FAlta) {
		this.FAlta = FAlta;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "F_MODIF", nullable = false, length = 19)
	public Date getFModif() {
		return this.FModif;
	}

	public void setFModif(Date FModif) {
		this.FModif = FModif;
	}

}
