package com.ks.entities;
// Generated 02-sep-2017 16:26:57 by Hibernate Tools 5.2.3.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Producto generated by hbm2java
 */
@Entity
@Table(name = "producto", catalog = "kumibd", uniqueConstraints = @UniqueConstraint(columnNames = "CODIGO"))
public class Producto implements java.io.Serializable {

	private long id;
	private String codigo;
	private Double precioActual;
	private String descripcion;
	private Date FAlta;
	private Date FModif;
	private Set<OrdenCompra> ordenCompras = new HashSet<OrdenCompra>(0);

	public Producto() {
	}

	public Producto(long id, String codigo, Date FAlta, Date FModif) {
		this.id = id;
		this.codigo = codigo;
		this.FAlta = FAlta;
		this.FModif = FModif;
	}

	public Producto(long id, String codigo, Double precioActual, String descripcion, Date FAlta, Date FModif,
			Set<OrdenCompra> ordenCompras) {
		this.id = id;
		this.codigo = codigo;
		this.precioActual = precioActual;
		this.descripcion = descripcion;
		this.FAlta = FAlta;
		this.FModif = FModif;
		this.ordenCompras = ordenCompras;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "CODIGO", unique = true, nullable = false, length = 7)
	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	@Column(name = "PRECIO_ACTUAL", precision = 20, scale = 0)
	public Double getPrecioActual() {
		return this.precioActual;
	}

	public void setPrecioActual(Double precioActual) {
		this.precioActual = precioActual;
	}

	@Column(name = "DESCRIPCION", length = 200)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "F_ALTA", nullable = false, length = 19)
	public Date getFAlta() {
		return this.FAlta;
	}

	public void setFAlta(Date FAlta) {
		this.FAlta = FAlta;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "F_MODIF", nullable = false, length = 19)
	public Date getFModif() {
		return this.FModif;
	}

	public void setFModif(Date FModif) {
		this.FModif = FModif;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "producto_orden", catalog = "kumibd", joinColumns = {
			@JoinColumn(name = "ID_PRODUCTO", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "ID_ORDEN_COMPRA", nullable = false, updatable = false) })
	public Set<OrdenCompra> getOrdenCompras() {
		return this.ordenCompras;
	}

	public void setOrdenCompras(Set<OrdenCompra> ordenCompras) {
		this.ordenCompras = ordenCompras;
	}

}
