package com.ks.entities;
// Generated 02-sep-2017 15:22:27 by Hibernate Tools 5.2.3.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Producto generated by hbm2java
 */
@Entity
@Table(name = "producto", catalog = "kumibd", uniqueConstraints = @UniqueConstraint(columnNames = "CODIGO"))
public class Producto implements java.io.Serializable {

	private long id;
	private String codigo;
	private String descripcion;
	private Date FAlta;
	private Date FModif;
	private Set<ProductoOrden> productoOrdens = new HashSet<ProductoOrden>(0);

	public Producto() {
	}

	public Producto(long id, String codigo, Date FAlta, Date FModif) {
		this.id = id;
		this.codigo = codigo;
		this.FAlta = FAlta;
		this.FModif = FModif;
	}

	public Producto(long id, String codigo, String descripcion, Date FAlta, Date FModif,
			Set<ProductoOrden> productoOrdens) {
		this.id = id;
		this.codigo = codigo;
		this.descripcion = descripcion;
		this.FAlta = FAlta;
		this.FModif = FModif;
		this.productoOrdens = productoOrdens;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "CODIGO", unique = true, nullable = false, length = 7)
	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	@Column(name = "DESCRIPCION", length = 200)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "F_ALTA", nullable = false, length = 19)
	public Date getFAlta() {
		return this.FAlta;
	}

	public void setFAlta(Date FAlta) {
		this.FAlta = FAlta;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "F_MODIF", nullable = false, length = 19)
	public Date getFModif() {
		return this.FModif;
	}

	public void setFModif(Date FModif) {
		this.FModif = FModif;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "producto")
	public Set<ProductoOrden> getProductoOrdens() {
		return this.productoOrdens;
	}

	public void setProductoOrdens(Set<ProductoOrden> productoOrdens) {
		this.productoOrdens = productoOrdens;
	}

}
